services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  server:
    container_name: server
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mysql:
        condition: service_healthy
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot -d $BASE_URL --agree-tos --email $CERT_EMAIL --non-interactive
    depends_on:
      - server
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certbot
volumes:
  mysql_data: